"""Phase H deployment asset generation and supervisor policy helpers."""
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from Shared.codex_client import get_codex_client
from Shared.config import Config


@dataclass(frozen=True)
class DeploymentAsset:
    """One deployment file to write to disk."""

    path: str
    content: str


class DeploymentManager:
    """Generates and writes deterministic deployment manifests."""

    def __init__(self, repo_root: str | Path) -> None:
        self.repo_root = Path(repo_root)

    def build_assets(self, use_codex: bool = True) -> list[DeploymentAsset]:
        """Build Docker/Compose/Supervisor assets.

        Uses Codex client opportunistically for a provenance comment only.
        """

        provenance = "generated-locally"
        if use_codex:
            client = get_codex_client()
            if client.is_available():
                summary = client.generate_text(
                    "Return a short deployment hardening note (max 12 words).",
                    max_tokens=24,
                )
                if summary:
                    provenance = summary.strip().replace("\n", " ")

        timestamp = datetime.now(timezone.utc).isoformat()
        dockerfile = (
            "FROM python:3.11-slim\n"
            "WORKDIR /app\n"
            "ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1\n"
            "COPY requirements.txt ./\n"
            "RUN pip install --no-cache-dir -r requirements.txt\n"
            "COPY . .\n"
            "EXPOSE 5000\n"
            "CMD [\"python\", \"Phase_A/api.py\"]\n"
        )
        compose = (
            "version: '3.9'\n"
            "services:\n"
            "  kalshiguard:\n"
            "    build: .\n"
            "    container_name: kalshiguard\n"
            "    restart: unless-stopped\n"
            "    env_file:\n"
            "      - .env\n"
            "    ports:\n"
            "      - \"5000:5000\"\n"
            "    volumes:\n"
            "      - ./:/app\n"
            "    healthcheck:\n"
            "      test: [\"CMD\", \"python\", \"scripts/healthcheck.py\"]\n"
            "      interval: 30s\n"
            "      timeout: 10s\n"
            "      retries: 3\n"
            "      start_period: 20s\n"
        )
        supervisor = (
            "; auto-generated by Shared.deployment\n"
            f"; {timestamp} | {provenance}\n"
            "[supervisord]\n"
            "nodaemon=true\n"
            "logfile=/tmp/supervisord.log\n\n"
            "[program:kalshiguard]\n"
            "directory=/app\n"
            "command=python Phase_A/api.py\n"
            "autostart=true\n"
            "autorestart=true\n"
            "startsecs=5\n"
            "stdout_logfile=/tmp/kalshiguard.out.log\n"
            "stderr_logfile=/tmp/kalshiguard.err.log\n"
        )

        return [
            DeploymentAsset(path="Dockerfile", content=dockerfile),
            DeploymentAsset(path="docker-compose.yml", content=compose),
            DeploymentAsset(path="Phase_H/supervisord.conf", content=supervisor),
        ]

    def write_assets(self, overwrite: bool = False, use_codex: bool = True) -> list[str]:
        """Write deployment assets to repository and return changed paths."""

        written: list[str] = []
        for asset in self.build_assets(use_codex=use_codex):
            file_path = self.repo_root / asset.path
            file_path.parent.mkdir(parents=True, exist_ok=True)
            if file_path.exists() and not overwrite:
                continue
            file_path.write_text(asset.content, encoding="utf-8")
            written.append(asset.path)
        return written

    @staticmethod
    def should_restart(error_streak: int) -> bool:
        """Supervisor-style restart rule from config threshold."""

        return error_streak >= Config.HEALTH_ERROR_STREAK_RESTART
